#!/bin/bash

function docker-run() {
    docker run -it ariesr91/kali-linux:full su -l Arie-SR91
}

function docker-commit() {
    read -p "Docker Id: " dockerid;
    docker commit $dockerid ariesr91/kali-linux:full
    docker container rm $dockerid
    docker image rm ariesr91/kali-rolling
    return 0
}

function docker-push() {
    docker push ariesr91/kali-linux:full
}

case $1 in
    login)
        docker-run
        ;;
    commit)
        docker-commit
        ;;
    push)
        docker-push
        ;;
esac
